name: SSH smoke test

on:
  workflow_dispatch: {} # lancement manuel

jobs:
  ssh-smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: |
            ${{ secrets.OVH_DEPLOY_KEY }}

      - name: Trust host
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H "${{ secrets.OVH_HOST }}" >> ~/.ssh/known_hosts

      - name: Ping VPS via SSH
        env:
          HOST: ${{ secrets.OVH_HOST }}
          USER: ${{ secrets.OVH_USER }}
        run: |
          ssh -o BatchMode=yes "${USER}@${HOST}" 'whoami && hostname && uptime'

# test
